# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "70c900bcc596cfc7748ac9f40b3fc5c9"
name = "track-this-product-hn-demo-3"
handle = "track-this-product-hn-demo-4"
application_url = "https://ukraine-natural-investigators-souls.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = ["https://ukraine-natural-investigators-souls.trycloudflare.com/auth/callback", "https://ukraine-natural-investigators-souls.trycloudflare.com/auth/shopify/callback", "https://ukraine-natural-investigators-souls.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
