# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4a984be3841b3aa266f4c8e9cb8cceb"
name = "track-this-product-hn-x"
handle = "track-this-product-hn-x-19"
application_url = "https://upgrades-annual-boats-award.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = ["https://upgrades-annual-boats-award.trycloudflare.com/auth/callback", "https://upgrades-annual-boats-award.trycloudflare.com/auth/shopify/callback", "https://upgrades-annual-boats-award.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
