# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2af376b81b83b84498455716a53b09a7"
name = "track-this-product-hn-x"
handle = "track-this-product-hn-x-10"
application_url = "https://spice-courtesy-madagascar-assists.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_inventory,write_products"

[auth]
redirect_urls = ["https://spice-courtesy-madagascar-assists.trycloudflare.com/auth/callback", "https://spice-courtesy-madagascar-assists.trycloudflare.com/auth/shopify/callback", "https://spice-courtesy-madagascar-assists.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
